name: learn-github-actions
run-name: ${{ github.actor }} is building new version
on:
  push:
    paths:
      - .github/release.version
permissions:
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read release.version
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/release.version

      - name: Echo release.version
        run: echo "New version is ${{ steps.package.outputs.content }}"

      - name: Build attachments
        run: |
          chmod +x ./.github/build.sh && VERSION=${{ steps.package.outputs.content }} ./.github/build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package.outputs.content }}
          prerelease: false
          draft: false
          files: dist/*
          generate_release_notes: true
          body: |
            <details>
              <summary>🤖 New version of ${{ steps.package.outputs.content }}</summary>
            </details>
