name: learn-github-actions
run-name: ${{ github.actor }} is building new release
on:
  push:
    paths:
      - release.version
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read release.version
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./release.version

      - name: Echo release.version
        run: echo "New version is ${{ steps.package.outputs.content }}"
