name: learn-github-actions
run-name: ${{ github.actor }} is building new version
on:
  push:
    paths:
      - release.version
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read release.version
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./release.version

      - name: Echo release.version
        run: echo "New version is ${{ steps.package.outputs.content }}"

      # - name: Build attachments
      #   run: |
      #     chmod +x build.sh
      #     CROSS_BUILD=true APP_NAME=${{ env.APP_NAME }} VERSION=${{ needs.changelog.outputs.version }} build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package.outputs.content }}
          prerelease: false
          draft: false
          files: dist/*
          generate_release_notes: true
          body: |
            <details>
              <summary>🤖 New version of ${{ steps.package.outputs.content }}</summary>
            </details>
